export enum Timezone {
    GMT = 'GMT',
    GMT_PLUS_1 = 'GMT+1',
    GMT_PLUS_2 = 'GMT+2',
    GMT_PLUS_3 = 'GMT+3',
    GMT_PLUS_4 = 'GMT+4',
    GMT_PLUS_5 = 'GMT+5',
    GMT_PLUS_6 = 'GMT+6',
    GMT_PLUS_7 = 'GMT+7',
    GMT_PLUS_8 = 'GMT+8',
    GMT_PLUS_9 = 'GMT+9',
    GMT_PLUS_10 = 'GMT+10',
    GMT_PLUS_11 = 'GMT+11',
    GMT_PLUS_12 = 'GMT+12',
    GMT_MINUS_1 = 'GMT-1',
    GMT_MINUS_2 = 'GMT-2',
    GMT_MINUS_3 = 'GMT-3',
    GMT_MINUS_4 = 'GMT-4',
    GMT_MINUS_5 = 'GMT-5',
    GMT_MINUS_6 = 'GMT-6',
    GMT_MINUS_7 = 'GMT-7',
    GMT_MINUS_8 = 'GMT-8',
    GMT_MINUS_9 = 'GMT-9',
    GMT_MINUS_10 = 'GMT-10',
    GMT_MINUS_11 = 'GMT-11',
    GMT_MINUS_12 = 'GMT-12',
}